### ISSUE TITLE
Error on slice/square bracket

### ISSUE THREAD

**Issue by Moon4u** [mattn/mruby-pcre-regexp#8]
````Ruby
> "0"[0]
.../mruby/mrbgems/mruby-regexp-pcre/mrblib/string_pcre.rb:140: stack level too deep. (limit=(0x40000 - 128)) (SystemStackError)
````
I'm guessing that alias_method for the square method is aliasing to the same method somehow.

**Comment by mattn** [comment]
Hmm, I can't reproduce it.

**Comment by Moon4u** [comment]
Yeah, it looks like it's something on my side. I tough that I have the mruby-pcre-regexp twice in my build_config, but this is not the case. Anyway, I'm going to close the issue as I don't think its specific to this gem.
